{
  PAIRS: {
    A: "0xbc9d21652cca70f54351e3fb982c6b5dbe992a22",
    B: "0xb4e16d0168e52d35cacd2c6185b44281ec28c9dc",
    TABLE_NAME: "IntoTheBlock",
  },
  UNISWAP_URL: "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2",
  CALL_INTERVAL_IN_SECONDS: 3600,
  INITIAL_CALL_INTERVAL_IN_SECONDS: 172800,
  AWS: {
    REGION: "us-east-1",
    ENDPOINT: "http://into-the-block.database:8000"
  },
  LOG_LEVEL: "info"
}
