openapi: 3.0.1
info:
  title: Pairs Service REST API
  version: v1
servers:
  - description: 'Local'
    url: 'http://localhost:8080'
tags:
  - description: Pairs
    name: pairs
paths:
  /api/pairs:
    get:
      description: This request retrieves all pairs
      operationId: getPairs
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pair'
          description: OK
        '401':
          description: Unauthorized
        '403':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
          description: Forbidden
      tags:
        - pairs
components:
  schemas:
    Pair:
      type: object
      properties:
        A:
          type: string
        B:
          type: string
    ErrorInfo:
      type: object
      properties:
        exception:
          type: string
        message:
          type: string
